### ISSUE TITLE
Continually prompting for update even when fully updated

### ISSUE THREAD

**Issue by thomasklash** [reds-heig/logisim-evolution#127]
The program continually prompts to update on launch, no matter what:
![image](https://user-images.githubusercontent.com/14216632/30521405-a203d804-9c02-11e7-949d-53773898b441.png)

**Comment by alexandremalki** [comment]
Hi,
It should be fixed by now. Would you please retry and let me know the status?
Thank you.
Have a nice day.

**Comment by thomasklash** [comment]
Still happens 
![image](https://user-images.githubusercontent.com/14216632/30627237-56a1d5fc-9e12-11e7-98c2-0af181dc2816.png)

**Comment by alexandremalki** [comment]
This is weird. Here on our side the problème is resolved.
So now please could you:

- You try to  update your logisim by pulling the last version? 
- Press yes. If the problem continues go then press no, and let me know your version.

Best regards

**Comment by thomasklash** [comment]
It goes away after pressing "Yes", but it should not be appearing at all

**Comment by alexandremalki** [comment]
What about you press no? This way i can just check the version you are running

**Comment by thomasklash** [comment]
I pressed no, I am running version 2.14.2, which I mentioned earlier :) latest commit compiled

**Comment by AerodynamicBrick** [comment]
I'm having the same issue. Keeps asking for update to .2 I'm on .1 tho?
Won't update

**Comment by alexandremalki** [comment]
Could you try to clean the directory (ant clean) and then rebuild it (ant build) and run (ant run) ?

Thank you

**Comment by alexandremalki** [comment]
Also, on what platform are you running?

**Comment by AerodynamicBrick** [comment]
Win10

**Comment by thomasklash** [comment]
I'm on Win7 x64

**Comment by alexandremalki** [comment]
Hi there,
I was thinking that maybe you on the wrong branch. Are you pulling from master?

**Comment by alexandremalki** [comment]
Ok from the source, oould you please checkout
git checkout /src/com/cburch/logisim/Main.java ?

If this does not work, could you check the version number in the file aforementioned?

**Comment by thomasklash** [comment]
After `ant clean` and `ant run` the new compiled `.jar` no longer has this issue.

**Comment by alexandremalki** [comment]
Good, happy it works
